{{- if .Values.infra -}}
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: {{ .Values.tenantId }}
  namespace: flux-system
spec:
  path: ./terraform/modules/tenant-apps
  interval: 1m
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: {{ .Values.infra.tfVersion }}
  vars:
    - name: tenant_id
      value: {{ .Values.tenantId }}
{{- range $key, $value := .Values.infra.vars }}
    - name: {{ $key }}
      value: {{ $value }}
{{- end }}
  writeOutputsToSecret:
    name: {{ .Values.tenantId }}-infra-output
{{ end }}