apiVersion: v1
kind: Namespace
metadata:
  name: pool-1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pool-1
  namespace: flux-system
spec:
  releaseName: pool-1
  targetNamespace: pool-1
  storageNamespace: pool-1
  interval: 1m0s
  chart:
    spec:
      chart: helm-tenant-chart
      version: 0.0.x
      sourceRef:
        kind: HelmRepository
        name: helm-tenant-chart
  values:
    tenantId: pool-1
    deployApps: true
    deployIngress: true # to simplify cleaning the stack
    producer.serviceAccount.annotations: "eks.amazonaws.com/role-arn: {pooled-1_producer_irsa_role}"
    consumer.serviceAccount.annotations: "eks.amazonaws.com/role-arn: {pooled-1_consumer_irsa_role}"