{{- if .Values.deployApps -}}
{{ range .Values.apps }}
{{ if (index $.Values .name).serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: "{{$.Chart.Name}}-{{$.Chart.Version }}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/version: "{{ $.Chart.AppVersion  }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
  {{- with (index $.Values.infraValues .name).irsa_role }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
