apiVersion: v1
kind: Namespace
metadata:
  name: {ENVIRONMENT_ID}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {ENVIRONMENT_ID}
  namespace: flux-system
spec:
  releaseName: {ENVIRONMENT_ID}
  targetNamespace: {ENVIRONMENT_ID}
  storageNamespace: {ENVIRONMENT_ID}
  interval: 1m0s
  chart:
    spec:
      chart: helm-tenant-chart
      version: "{RELEASE_VERSION}.x"
      sourceRef:
        kind: HelmRepository
        name: helm-tenant-chart
  values:
    tenantId: {ENVIRONMENT_ID}
    awsAccountId: "127913424329"
    infra:
      vars:
        enable_producer: true
        enable_consumer: true
    apps:
      producer:
        enabled: true
      consumer:
        enabled: true