apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tenant-deployment-
  namespace: argo-workflows
spec:
  serviceAccountName: argoworkflows-sa
  entrypoint: tenant-deployment
  synchronization:
    mutex:
      name: workflow
  arguments:
    parameters:
      - name: TENANT_MODEL
        value: "" # Valid values are: silo, pool, hybrid
      - name: RELEASE_VERSION
        value: "1.0" # Valid values are: silo, pool, hybrid
      - name: REPO_URL
        value: "{REPO_URL}"
      - name: GIT_USER_EMAIL
        value: "{CODECOMMIT_USER_ID}"
      - name: GIT_USERNAME
        value: "{CODECOMMIT_USER_ID}"
      - name: GIT_BRANCH
        value: "main" # Can change based on your configs
  templates:
    - name: tenant-deployment
      steps:
        - - name: clone-repository
            templateRef:
              name: tenant-deployment-template
              template: clone-repository
        - - name: update-tenant-infrastructure
            templateRef:
              name: tenant-deployment-template
              template: update-tenant-infrastructure
        - - name: update-tenant-helm-release
            templateRef:
              name: tenant-deployment-template
              template: update-tenant-helm-release
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  volumes:
    - name: ssh-key
      secret:
        secretName: github-ssh-key # Secret created earlier
        items:
          - key: ssh-privatekey
            path: id_rsa
